// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFk3dDwtcpIagMnL_X3MEHmwaoCUHAzuk',
    appId: '1:416048377225:web:dc346e4d5dda19fd8d4558',
    messagingSenderId: '416048377225',
    projectId: 'test-grad-project',
    authDomain: 'test-grad-project.firebaseapp.com',
    storageBucket: 'test-grad-project.firebasestorage.app',
    measurementId: 'G-LBRGGC8PKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6vFOa_8SE_NuEmkJPRmY61fv0iUENpI',
    appId: '1:416048377225:android:298bff098bad02488d4558',
    messagingSenderId: '416048377225',
    projectId: 'test-grad-project',
    storageBucket: 'test-grad-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtWOznEhoRxTD7TzkgrKrsysqhhV9BWY',
    appId: '1:416048377225:ios:24b9b98fb91158a58d4558',
    messagingSenderId: '416048377225',
    projectId: 'test-grad-project',
    storageBucket: 'test-grad-project.firebasestorage.app',
    iosBundleId: 'com.example.roadSenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtWOznEhoRxTD7TzkgrKrsysqhhV9BWY',
    appId: '1:416048377225:ios:24b9b98fb91158a58d4558',
    messagingSenderId: '416048377225',
    projectId: 'test-grad-project',
    storageBucket: 'test-grad-project.firebasestorage.app',
    iosBundleId: 'com.example.roadSenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFk3dDwtcpIagMnL_X3MEHmwaoCUHAzuk',
    appId: '1:416048377225:web:08bc67bbdd4d68e78d4558',
    messagingSenderId: '416048377225',
    projectId: 'test-grad-project',
    authDomain: 'test-grad-project.firebaseapp.com',
    storageBucket: 'test-grad-project.firebasestorage.app',
    measurementId: 'G-KRJ57B0PMB',
  );
}
